### ISSUE TITLE
Maintainer wanted ❤️

### ISSUE THREAD

**Issue by isRuslan** [isRuslan/awesome-elm#172]
Awesome Elm is looking for a new maintainer to lead and support this list.
This list is activity updating and used by other people. At this moment its up to 3K ⭐️.

A new maintainer desirable profile:
- elm coding experience
- involved in community
- being ready to spend your free time to support elm

If you feel yourself ready please send me an email to [is.ismagilov@gmail.com](mailto:is.ismagilov@gmail.com?subject=ElmMaintainer) with short introduction of yourself.

Thank you!

**Comment by razzeee** [comment]
Another thing to consider might be to move this to an org like elm-community?

**Comment by alexkorban** [comment]
I sent you an email. Happy to take over maintenance.

**Comment by isRuslan** [comment]
> Another thing to consider might be to move this to an org like elm-community?

I'd happy to move to https://github.com/elm-community if someone from an org approve it.

**Comment by jah2488** [comment]
I think moving to `elm-community` is a great idea. If it doesn't end up going that route, (or being adopted by Alex), then I'd be happy to maintain the project. I'm already maintaining `elm-companies` list.

**Comment by BrianHicks** [comment]
Hi folks, just want to drop in and ask that this please not move to elm-community. It's a fine organization, but a list like this has a strong sense of personal curation. I trust @isRuslan's picks or @alexkorban's picks way more as personal recommendations than as things made on behalf of the entire community! That way, I get to evaluate based on the listed author just the same as most packages in the ecosystem.

Besides that, elm-community has historically been a place where the community has forked repos to upgrade them when the original maintainers were no longer responsive. These haven't been hostile forks, but made practically in service of unblocking upgrades etc. This is not that situation, so maybe it doesn't make sense to take the same action.

**Comment by razzeee** [comment]
While I felt like I kinda agree at first some of your wording bothers me, or at least causes new questions.

Do you really expect a curation from an `awesome list`? The ones I used so far more seemed like a place to get a quick overview, not a recommendation.
The only list I can think of that was kinda different was one that had the prerequisite of your project having tests. So that did filter out some stuff.

So your basically saying whoever takes this over should look at each PR he get's, poke around with it and test it? Then decide if they include it or deny the inclusion?

**Comment by BrianHicks** [comment]
Yes, I think that's basically true. The description of this repo starts "A curated list of useful Elm tutorials, libraries and software. Inspired by awesome list." It's got to say no to some things, right? Otherwise, it would be the same as package.elm-lang.org or elm-news.com—both nice resources, but by their nature more comprehensive than a place to highlight *awesome* work.

For what it's worth, I think Alex is the person for the job here. Working with him on Elm Weekly (which also has this nature) has been great! He's got a great sense of what and and what not to include. I think the awesome list would benefit from his involvement. 😁

**Comment by alexkorban** [comment]
Thanks for the vote of confidence @BrianHicks :) This discussion might be of purely academic interest in the absence of participation from @isRuslan (it's his repo and his decision after all). 

FWIW, my idea of curation would be to keep the list up to date as new versions of Elm come out, and to focus on "chunkier" resources, eg a list of podcasts rather than podcast episodes, a list of conference video channels instead of individual videos, etc. I figured that since I keep up with most of this stuff due to my work on Elm Weekly and general involvement with Elm anyway, it shouldn't be too onerous for me to maintain this list. 

I think the existing sections in the list are pretty much fine, they just really need to be brought up to date.

**Comment by dainmiller** [comment]
Awesome @isRuslan  - looks like you've got a well regarded maintainer to set up here. Let's get him set up and close this issue out :)

**Comment by isRuslan** [comment]
A new maintainer is Sebastian Porto (@sporto) 👏 

This repository is being transferred to @sporto account.
Congrats and good luck Sebastian!
